# Generated by Django 6.0.4 on 2026-04-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bollywood", "Bollywood"),
                            ("hollywood", "Hollywood"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=10, unique=True)),
                ("status", models.CharField(default="waiting", max_length=20)),
                ("team_a_score", models.IntegerField(default=0)),
                ("team_b_score", models.IntegerField(default=0)),
                ("current_selecting_team", models.CharField(default="A", max_length=1)),
                ("current_guessing_team", models.CharField(default="B", max_length=1)),
                (
                    "selected_movie",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("hint_giver_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(blank=True, max_length=1, null=True)),
                ("is_host", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.room",
                    ),
                ),
            ],
        ),
    ]
