# Generated by Django 6.0.4 on 2026-04-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="room",
            name="phase",
            field=models.CharField(default="category_selection", max_length=30),
        ),
        migrations.AddField(
            model_name="room",
            name="round_time",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="room",
            name="total_rounds",
            field=models.IntegerField(default=5),
        ),
    ]
