# Generated by Django 6.0.4 on 2026-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_room_current_round_room_phase_room_round_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="phase",
            field=models.CharField(default="waiting", max_length=30),
        ),
    ]
