# Generated by Django 6.0.4 on 2026-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_room_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("place", "Place"),
                            ("person", "Person"),
                            ("food", "Food"),
                            ("fruit", "Fruit"),
                            ("vegetable", "Vegetable"),
                            ("animal", "Animal"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="selected_movie",
            new_name="selected_word",
        ),
        migrations.RemoveField(
            model_name="room",
            name="round_time",
        ),
        migrations.AddField(
            model_name="player",
            name="avatar",
            field=models.CharField(default="🐶", max_length=10),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
