# Generated by Django 6.0.4 on 2026-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_word_delete_movie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="round_time",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="room",
            name="selected_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
