# Generated by Django 6.0.4 on 2026-04-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_room_round_time_room_selected_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="word_options_count",
            field=models.IntegerField(default=3),
        ),
    ]
