# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_room_word_options_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="round_started_at",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
