# Generated by Django 6.0.4 on 2026-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_room_round_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="allow_random",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="max_players",
            field=models.IntegerField(default=4),
        ),
    ]
