from django.core.management.base import BaseCommand
from game.models import Word


class Command(BaseCommand):
    help = "Seed words for GuessVerse"

    def handle(self, *args, **kwargs):
        data = {
            "movie": ["3 Idiots", "Dangal", "Sholay", "PK", "Lagaan",
            "Jawan", "Pathaan", "War", "Queen", "Barfi",
            "Andhadhun", "Drishyam", "Krrish", "Don", "Raees",
            "Gully Boy", "Chak De India", "Zindagi Na Milegi Dobara",
            "Kabhi Khushi Kabhie Gham", "Yeh Jawaani Hai Deewani",
            "Dilwale Dulhania Le Jayenge", "Kal Ho Naa Ho", "Kuch Kuch Hota Hai",
            "Bajrangi Bhaijaan", "Sultan", "Tiger Zinda Hai", "Ek Tha Tiger",
            "Kabir Singh", "Rockstar", "Tamasha", "Swades", "Rang De Basanti",
            "Taare Zameen Par", "Munna Bhai MBBS", "Sanju", "Stree",
            "Bhool Bhulaiyaa", "Hera Pheri", "Welcome", "Golmaal",
            "Dil Chahta Hai", "Om Shanti Om", "My Name Is Khan",
            "Brahmastra", "Animal", "12th Fail", "Kantara", "Pushpa",
            "Baahubali", "RRR","Titanic", "Avatar", "Inception", "Interstellar",
            "The Dark Knight","Joker", "Frozen", "The Lion King", "Jurassic Park",
            "Harry Potter","Avengers Endgame", "Spider Man", "Iron Man", "Black Panther",
            "Finding Nemo", "Toy Story", "The Conjuring", "Mission Impossible",
            "Fast and Furious", "Pirates of the Caribbean", "The Avengers",
            "Doctor Strange", "Thor Ragnarok", "Captain America", "Wonder Woman",
            "Aquaman", "Batman Begins", "Superman", "The Matrix", "John Wick",
            "The Godfather", "Forrest Gump", "The Shawshank Redemption",
            "Fight Club", "The Hangover", "Home Alone", "The Nun",
            "Annabelle", "IT", "The Exorcist", "La La Land", "Oppenheimer",
            "Barbie", "The Wolf of Wall Street", "The Social Network",
            "The Martian", "Gravity", "Mad Max Fury Road", "King Kong",
            "Godzilla"],
            "place":[ "Taj Mahal", "India Gate", "Red Fort", "Qutub Minar", "Gateway of India",
            "Hawa Mahal", "Charminar", "Golden Temple", "Lotus Temple", "Mysore Palace",
            "Victoria Memorial", "Howrah Bridge", "Marine Drive", "Jantar Mantar",
            "Ajanta Caves", "Ellora Caves", "Konark Sun Temple", "Meenakshi Temple",
            "Rameswaram", "Kedarnath", "Badrinath", "Vaishno Devi",
            "Varanasi", "Rishikesh", "Haridwar", "Goa", "Manali", "Shimla",
            "Leh Ladakh", "Srinagar", "Dal Lake", "Udaipur", "Jaipur", "Jodhpur",
            "Pushkar", "Amritsar", "Chandigarh", "Darjeeling", "Gangtok",
            "Andaman Islands", "Lakshadweep", "Coorg", "Ooty", "Kodaikanal",
            "Munnar", "Alleppey", "Wayanad", "Hampi", "Pondicherry",
            "Eiffel Tower", "Statue of Liberty", "Great Wall of China",
            "Colosseum", "Leaning Tower of Pisa", "Big Ben", "Buckingham Palace",
            "Tower Bridge", "London Eye", "Burj Khalifa", "Burj Al Arab",
            "Palm Jumeirah", "Petra", "Machu Picchu", "Christ the Redeemer",
            "Niagara Falls", "Grand Canyon", "Mount Everest", "Mount Fuji",
            "Sydney Opera House", "Great Barrier Reef", "Times Square",
            "Central Park", "Hollywood Sign", "Golden Gate Bridge",
            "Las Vegas Strip", "Disneyland", "Universal Studios",
            "White House", "Capitol Building", "Alcatraz Island",
            "Angkor Wat", "Banff National Park", "Santorini", "Acropolis",
            "Neuschwanstein Castle", "Versailles Palace", "Louvre Museum",
            "Stonehenge", "Glacier National Park", "Yellowstone National Park",
            "Amazon Rainforest", "Sahara Desert", "Antarctica", "North Pole",
            "South Pole", "Maldives", "Bali", "Phuket", "Dubai Marina"],
            "person": [ "Naruto", "Bill Gates", "Tom Cruise", "Elsa", "Rohit Sharma",
            "Sherlock Holmes", "Deadpool", "Drake", "Alia Bhatt", "Scooby Doo",
            "Goku", "Kylian Mbappe", "Dwayne Johnson", "Pikachu", "Ranbir Kapoor",
            "Walter White", "Jeff Bezos", "Hulk", "Amitabh Bachchan", "Motu",
            "Angelina Jolie", "SpongeBob", "Priyanka Chopra", "Batman",
            "Subhas Chandra Bose", "Leonardo DiCaprio", "Jon Snow",
            "Cristiano Ronaldo", "Goofy", "Scarlett Johansson",
            "Ash Ketchum", "Mickey Mouse", "Elon Musk", "Chhota Bheem",
            "Robert Downey Jr", "Iron Man", "Luffy", "Anushka Sharma",
            "Napoleon Bonaparte", "Taylor Swift", "Shah Rukh Khan",
            "Captain America", "Rani Lakshmi Bai", "Messi", "Jack Sparrow",
            "Virat Kohli", "Selena Gomez", "Bhagat Singh", "Thor",
            "Kareena Kapoor", "Patrick Star", "Shinchan", "Brad Pitt",
            "Deepika Padukone", "Donald Duck", "Abraham Lincoln",
            "Justin Bieber", "Harry Potter", "Nobita", "James Bond",
            "Akshay Kumar", "Hattori", "Mark Zuckerberg", "Julius Caesar",
            "Chris Hemsworth", "Superman", "Aamir Khan", "Cleopatra",
            "Ranveer Singh", "Bugs Bunny", "Isaac Newton", "Hermione Granger",
            "Hrithik Roshan", "Tom", "Jerry", "Mahatma Gandhi",
            "MS Dhoni", "Salman Khan", "Daenerys Targaryen", "Ben 10",
            "Oppenheimer", "Albert Einstein", "Patlu", "Anna",
            "Katrina Kaif", "Lord Voldemort", "Spider Man", "Olaf",
            "Jawaharlal Nehru", "Indiana Jones", "Tiger Shroff",
            "Ronaldo", "Zayn Malik", "Johnny Depp", "Emma Watson"],
            "food": ["Pizza", "Burger", "Biryani", "Momos", "Dosa"],
            "fruit": ["Apple", "Banana", "Mango", "Orange", "Grapes",
            "Pineapple", "Strawberry", "Watermelon", "Papaya", "Guava",
            "Kiwi", "Blueberry", "Blackberry", "Raspberry", "Cherry",
            "Peach", "Plum", "Apricot", "Pear", "Pomegranate",
            "Coconut", "Lemon", "Lime", "Tangerine", "Cranberry",
            "Dragon Fruit", "Lychee", "Jackfruit", "Durian", "Passion Fruit",
            "Fig", "Date", "Mulberry", "Starfruit", "Persimmon",
            "Avocado", "Gooseberry", "Currant", "Elderberry", "Boysenberry",
            "Longan", "Rambutan", "Mangosteen", "Sapodilla", "Custard Apple",
            "Soursop", "Breadfruit", "Tamarind", "Quince", "Jujube",
            "Olive", "Kumquat", "Cantaloupe", "Honeydew", "Nectarine",
            "Pomelo", "Ugli Fruit", "Yuzu", "Salak", "Miracle Fruit",
            "Ackee", "Feijoa", "Loquat", "Medlar", "Barberry",
            "Cloudberry", "Huckleberry", "Lingonberry", "Serviceberry", "Sea Buckthorn",
            "Physalis", "Bilberry", "Jabuticaba", "Cupuaçu", "Atemoya",
            "Cherimoya", "Kiwano", "Bael", "Wood Apple", "Langsat",
            "Santol", "Marula", "Baobab Fruit", "Horned Melon", "Monstera Fruit",
            "Ice Apple", "Indian Fig", "Sugar Apple", "Rose Apple", "Java Plum",
            "Palm Fruit", "African Cucumber", "Black Sapote", "White Sapote",
            "Canistel", "Surinam Cherry", "Malay Apple", "Mountain Apple", "Illawarra Plum"],
            "vegetable": [
            "Potato", "Tomato", "Onion", "Carrot", "Cabbage",
            "Cauliflower", "Broccoli", "Spinach", "Lettuce", "Beetroot",
            "Radish", "Turnip", "Peas", "Green Beans", "Capsicum",
            "Bell Pepper", "Chilli", "Cucumber", "Zucchini", "Eggplant",
            "Brinjal", "Pumpkin", "Bottle Gourd", "Ridge Gourd", "Bitter Gourd",
            "Snake Gourd", "Ash Gourd", "Drumstick", "Okra", "Lady Finger",
            "Sweet Potato", "Yam", "Taro", "Colocasia", "Garlic",
            "Ginger", "Spring Onion", "Leek", "Shallot", "Celery",
            "Parsley", "Coriander", "Mint", "Fenugreek", "Mustard Greens",
            "Kale", "Swiss Chard", "Arugula", "Endive", "Artichoke",
            "Asparagus", "Brussels Sprouts", "Fennel", "Horseradish", "Parsnip",
            "Kohlrabi", "Turnip Greens", "Collard Greens", "Watercress", "Bok Choy",
            "Chinese Cabbage", "Napa Cabbage", "Chayote", "Jicama", "Cassava",
            "Lotus Root", "Bamboo Shoots", "Green Papaya", "Raw Banana", "Raw Mango",
            "Green Peppers", "Red Peppers", "Yellow Peppers", "Purple Cabbage", "Red Cabbage",
            "White Radish", "Daikon", "Microgreens", "Pea Shoots", "Alfalfa Sprouts",
            "Bean Sprouts", "Chickpea Leaves", "Amaranth Leaves", "Malabar Spinach", "Sorrel",
            "Drumstick Leaves", "Pumpkin Leaves", "Banana Stem", "Banana Flower", "Elephant Foot Yam",
            "Winged Beans", "Cluster Beans", "French Beans", "Broad Beans", "Snow Peas",
            "Water Chestnut", "Tiger Nut", "Crosne", "Salsify", "Jerusalem Artichoke"],
            "animal": [
            "Lion", "Tiger", "Elephant", "Leopard", "Cheetah",
            "Bear", "Wolf", "Fox", "Hyena", "Jackal",
            "Dog", "Cat", "Cow", "Buffalo", "Goat",
            "Sheep", "Horse", "Donkey", "Camel", "Pig",
            "Rabbit", "Deer", "Moose", "Reindeer", "Zebra",
            "Giraffe", "Kangaroo", "Koala", "Panda", "Sloth",
            "Monkey", "Chimpanzee", "Gorilla", "Baboon", "Orangutan",
            "Otter", "Beaver", "Hedgehog", "Mole", "Raccoon",
            "Skunk", "Armadillo", "Porcupine", "Squirrel", "Bat",
            "Whale", "Dolphin", "Shark", "Octopus", "Squid",
            "Crab", "Lobster", "Seal", "Walrus", "Sea Lion",
            "Penguin", "Eagle", "Hawk", "Falcon", "Owl",
            "Parrot", "Sparrow", "Pigeon", "Peacock", "Flamingo",
            "Swan", "Duck", "Goose", "Turkey", "Woodpecker",
            "Crow", "Kingfisher", "Hornbill", "Vulture", "Albatross",
            "Snake", "Cobra", "Python", "Lizard", "Gecko",
            "Crocodile", "Alligator", "Turtle", "Tortoise", "Chameleon",
            "Frog", "Toad", "Salamander", "Newt", "Axolotl",
            "Ant", "Bee", "Butterfly", "Spider", "Scorpion",
            "Grasshopper", "Dragonfly", "Beetle", "Ladybug", "Termite"]
        }

        for category, words in data.items():
            for word in words:
                Word.objects.get_or_create(name=word, category=category)

        self.stdout.write(self.style.SUCCESS("Words added successfully"))